services:
  web:
    build: .
    restart: always
    volumes: 
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - db_volume:/app/db
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    networks:
      - beisi-network
    env_file:
      - .env

volumes:
  static_volume: {}   
  media_volume: {}    
  db_volume: {}

networks: # 自定义网络配置
  beisi-network: # 网络名称
    driver: bridge # 使用桥接模式网络
    name: beisi-shared-network # 指定网络别名
